name: Build and Archive iOS App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v2

    # Check the Xcode version installed on the runner
    - name: Check Xcode Version
      run: xcodebuild -version

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0' # Make sure this matches the version you're using

    - name: Clean Workloads Cache
      run: |
        dotnet workload clean
        dotnet workload install maui-ios --skip-manifest-update

    - name: Install .NET MAUI Workloads
      run: |
        dotnet workload install maui-android maui-ios maccatalyst

    - name: Restore dependencies
      run: dotnet restore

    - name: Build iOS Project (without signing)
      run: |
        dotnet build SNGPL/SNGPL.csproj -c Release -f:net8.0-ios -nowarn:0414 /p:MtouchCodeSign=false /p:CodesignKey="" /p:ProvisioningProfileUuid=""

    - name: Publish the iOS Project (IPA without signing)
      run: |
        dotnet publish SNGPL/SNGPL.csproj -c Release -f:net8.0-ios -o ./output -r ios-arm64 /p:MtouchCodeSign=false /p:RuntimeIdentifier=ios-arm64 /p:PlatformTarget=arm64 /p:PublishTrimmed=true /p:CodesignKey="" /p:ProvisioningProfileUuid="" /p:EnableCodeSigning=false
        mkdir -p ./build/ios  # Create the target directory if it doesn't exist
        mv ./output/*.ipa ./build/ios/SNGPL.ipa

    - name: Upload IPA as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: iOS-IPA
        path: ./output/SNGPL.ipa
