name: Build and Archive iOS App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v2

    # Check the Xcode version installed on the runner
    - name: Check Xcode Version
      run: xcodebuild -version

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0' # Make sure this matches the version you're using

    - name: Clean Workloads Cache
      run: |
        dotnet workload clean
        dotnet workload install maui-ios --skip-manifest-update

    - name: Install .NET MAUI Workloads
      run: |
        dotnet workload install maui-android maui-ios maccatalyst

    - name: Restore dependencies
      run: dotnet restore

    # Import iOS Code Signing Certificate with debugging
    - name: Import iOS Code Signing Certificate
      run: |
        # Decode and save the certificate
        echo "$IOS_CERTIFICATE" | base64 --decode > certificate.p12
        # Check if the certificate file was decoded successfully
        ls -l certificate.p12

        # Create a temporary keychain
        security create-keychain -p "" build.keychain
        security list-keychains -d user
        security unlock-keychain -p "" build.keychain

        # Import the certificate and private key (use the correct password for the certificate if needed)
        security import certificate.p12 -k build.keychain -P "" -T /usr/bin/codesign

        # Check if the certificate was added successfully
        security find-certificate -a -p build.keychain
        security list-keychains -d user

    # Build the iOS Project
    - name: Build iOS Project
      run: dotnet build SNGPL/SNGPL.csproj -c Release -f:net8.0-ios -nowarn:0414

    # Publish the iOS Project (IPA)
    - name: Publish the iOS Project (IPA)
      run: |
        dotnet publish SNGPL/SNGPL.csproj -c Release -f:net8.0-ios -o ./output -r ios-arm64 /p:RuntimeIdentifier=ios-arm64 /p:PlatformTarget=arm64 /p:MtouchLink=None /p:LinkerBehavior=LinkFramework
        mv ./bin/Release/net8.0-ios/ios-arm64/*.ipa ./build/ios/SNGPL.ipa
